pull_request_rules:
  - name: Label 'automerge' to PR to merge
    description: Add a label to a pull request that has to be merged
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: merge

  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued

  - name: Ping PR author when conflicting
    description: Warn the pull request author when their PR are conflicting
    conditions:
      - conflict
      - '-closed'
    actions:
      comment:
        message: |
          👋 {{author}} your PR is conflicting and needs to be updated to be merged

  - name: Make sure PR are up to date before merging
    description: >-
      This automatically updates PRs when they are out-of-date with the base branch
      to avoid semantic conflicts (next step is using a merge queue).
    conditions: []
    actions:
      update:

  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - '-closed'
    actions:
      label:
        toggle:
          - conflict